/* Drop Tables */

DROP TABLE IF EXISTS SCORE_HOLE;
DROP TABLE IF EXISTS SCORE;
DROP TABLE IF EXISTS ROUNDGROUP;
DROP TABLE IF EXISTS COMPE;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS SITEINFO;




/* Create Tables */

CREATE TABLE COMPE
(
	-- コンペID 
	COMPE_ID INTEGER NOT NULL UNIQUE,
	-- コンペの名称
	COMPE_NAME TEXT DEFAULT 'コンペ' NOT NULL,
	-- 開催場所
	SITE_ID INTEGER DEFAULT 0,
	-- 開催日
	DAYDATE DATE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (COMPE_ID)
) WITHOUT OIDS;


CREATE TABLE PERSON
(
	P_ID INTEGER NOT NULL UNIQUE,
	-- 氏名
	NAME TEXT,
	-- ニックネーム
	NICK_NAME TEXT,
	HDCP INTEGER DEFAULT 0,
	PRIMARY KEY (P_ID)
) WITHOUT OIDS;


CREATE TABLE ROUNDGROUP
(
	-- グループ名 ASCII
	GROUP_ID INTEGER NOT NULL UNIQUE,
	-- グループ名 (日本語)
	GROUP_NAME TEXT,
	-- コンペ名
	COMPE_ID INTEGER,
	PRIMARY KEY (GROUP_ID)
) WITHOUT OIDS;


CREATE TABLE SCORE
(
	ID INTEGER NOT NULL UNIQUE,
	-- グループ名 ASCII
	GROUP_ID INTEGER DEFAULT 0,
	PLAYER INTEGER NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SCORE_HOLE
(
	SCORE_CARD INTEGER NOT NULL,
	HOLE_NUM INTEGER,
	TOTAL INTEGER,
	PUTT INTEGER
) WITHOUT OIDS;


CREATE TABLE SITEINFO
(
	ID INTEGER NOT NULL UNIQUE,
	-- 名称
	NAME TEXT,
        -- バー
	HOLEPAR_OUT TEXT,
	HOLEPAR_IN TEXT,
	-- HDCP
	HDCP_OUT TEXT,
	HDCP_IN TEXT,
        -- 距離 レギュラー
	LENGTH_OUT TEXT,
	LENGTH_IN TEXT,
        -- 距離 ロング
	L_LENGTH_OUT TEXT,
	L_LENGTH_IN TEXT,
        -- 距離 ショート
	S_LENGTH_OUT TEXT,
	S_LENGTH_IN TEXT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


/* Create Foreign Keys */

ALTER TABLE ROUNDGROUP
	ADD FOREIGN KEY (COMPE_ID)
	REFERENCES COMPE (COMPE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SCORE
	ADD FOREIGN KEY (PLAYER)
	REFERENCES PERSON (P_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SCORE
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES ROUNDGROUP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SCORE_HOLE
	ADD FOREIGN KEY (SCORE_CARD)
	REFERENCES SCORE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPE
	ADD FOREIGN KEY (SITE_ID)
	REFERENCES SITEINFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN COMPE.COMPE_ID IS 'コンペID ';
COMMENT ON COLUMN COMPE.COMPE_NAME IS 'コンペの名称';
COMMENT ON COLUMN COMPE.SITE_ID IS '開催場所';
COMMENT ON COLUMN COMPE.DAYDATE IS '開催日';
COMMENT ON COLUMN PERSON.NAME IS '氏名';
COMMENT ON COLUMN PERSON.NICK_NAME IS 'ニックネーム';
COMMENT ON COLUMN ROUNDGROUP.GROUP_ID IS 'グループ名 ASCII';
COMMENT ON COLUMN ROUNDGROUP.GROUP_NAME IS 'グループ名 (日本語)';
COMMENT ON COLUMN ROUNDGROUP.COMPE_ID IS 'コンペ名';
COMMENT ON COLUMN SCORE.GROUP_ID IS 'グループ名 ASCII';
COMMENT ON COLUMN SITEINFO.NAME IS '名称';

